<?php
/**
 * Theme import config file.
 *
 * @var array
 *
 * @package Ocularis
 */
$config = array(
	'xml' => false,
	'advanced_import' => array(
		'default' => array(
			'label'    => esc_html__( 'Ocularis', 'ocularis' ),
			'full'     => 'http://monstroid.zemez.io/download/ocularis/default/default.xml',
			'lite'     => false,
			'thumb'    => 'http://monstroid.zemez.io/download/ocularis/default/default.jpg',
			'demo_url' => 'https://ld-wp73.template-help.com/ocularis/default',
		),
		'startup' => array(
			'label'    => esc_html__( 'Startup', 'ocularis' ),
			'full'     => 'http://monstroid.zemez.io/download/ocularis/startup/startup.xml',
			'lite'     => false,
			'thumb'    => 'http://monstroid.zemez.io/download/ocularis/startup/startup.jpg',
			'demo_url' => 'https://ld-wp73.template-help.com/ocularis/startup',
		),
		'coworking' => array(
			'label'    => esc_html__( 'Coworking', 'ocularis' ),
			'full'     => 'http://monstroid.zemez.io/download/ocularis/coworking/coworking.xml',
			'lite'     => false,
			'thumb'    => 'http://monstroid.zemez.io/download/ocularis/coworking/coworking.jpg',
			'demo_url' => 'https://ld-wp73.template-help.com/ocularis/coworking/',
		),
		'corporatelanding' => array(
			'label'    => esc_html__( 'Corporatelanding', 'ocularis' ),
			'full'     => 'http://monstroid.zemez.io/download/ocularis/corporatelanding/corporatelanding.xml',
			'lite'     => false,
			'thumb'    => 'http://monstroid.zemez.io/download/ocularis/corporatelanding/corporatelanding.jpg',
			'demo_url' => 'https://ld-wp73.template-help.com/ocularis/corporatelanding',
		),
		'cryptocurrency' => array(
			'label'    => esc_html__( 'Cryptocurrency', 'ocularis' ),
			'full'     => 'http://monstroid.zemez.io/download/ocularis/cryptocurrency/cryptocurrency.xml',
			'lite'     => false,
			'thumb'    => 'http://monstroid.zemez.io/download/ocularis/cryptocurrency/cryptocurrency.jpg',
			'demo_url' => 'https://ld-wp73.template-help.com/ocularis/cryptocurrency',
		),
		'digital' => array(
			'label'    => esc_html__( 'Digital', 'ocularis' ),
			'full'     => 'http://monstroid.zemez.io/download/ocularis/digital/digital.xml',
			'lite'     => false,
			'thumb'    => 'http://monstroid.zemez.io/download/ocularis/digital/digital.jpg',
			'demo_url' => 'https://ld-wp73.template-help.com/ocularis/digital',
		),
		'experience' => array(
			'label'    => esc_html__( 'Experience', 'ocularis' ),
			'full'     => 'http://monstroid.zemez.io/download/ocularis/experience/experience.xml',
			'lite'     => false,
			'thumb'    => 'http://monstroid.zemez.io/download/ocularis/experience/experience.jpg',
			'demo_url' => 'https://ld-wp73.template-help.com/ocularis/experience',
		),
		'finance' => array(
			'label'    => esc_html__( 'Finance', 'ocularis' ),
			'full'     => 'http://monstroid.zemez.io/download/ocularis/finance/finance.xml',
			'lite'     => false,
			'thumb'    => 'http://monstroid.zemez.io/download/ocularis/finance/finance.jpg',
			'demo_url' => 'https://ld-wp73.template-help.com/ocularis/finance',
		),
		'presentation' => array(
			'label'    => esc_html__( 'Presentation', 'ocularis' ),
			'full'     => 'http://monstroid.zemez.io/download/ocularis/presentation/presentation.xml',
			'lite'     => false,
			'thumb'    => 'http://monstroid.zemez.io/download/ocularis/presentation/presentation.jpg',
			'demo_url' => 'https://ld-wp73.template-help.com/ocularis/presentation',
		),
		'shop' => array(
			'label'    => esc_html__( 'Shop', 'ocularis' ),
			'full'     => 'http://monstroid.zemez.io/download/ocularis/shop/shop.xml',
			'lite'     => false,
			'thumb'    => 'http://monstroid.zemez.io/download/ocularis/shop/shop.jpg',
			'demo_url' => 'https://ld-wp73.template-help.com/ocularis/shop',
		),
		'blog' => array(
			'label'    => esc_html__( 'Blog', 'ocularis' ),
			'full'     => 'http://monstroid.zemez.io/download/ocularis/blog/blog.xml',
			'lite'     => false,
			'thumb'    => 'http://monstroid.zemez.io/download/ocularis/blog/blog.jpg',
			'demo_url' => 'https://ld-wp73.template-help.com/ocularis/blog',
		),
		'ocularis' => array(
			'label'    => esc_html__( 'Ocularis', 'ocularis' ),
			'full'     => 'http://monstroid.zemez.io/download/ocularis/ocularis/ocularis.xml',
			'lite'     => false,
			'thumb'    => 'http://monstroid.zemez.io/download/ocularis/default/default.jpg',
			'demo_url' => 'https://ld-wp73.template-help.com/ocularis/ocularis',
		),


	),
	'import' => array(
		'chunk_size' => 3,
	),
	'slider' => array(
		'path' => 'https://raw.githubusercontent.com/JetImpex/wizard-slides/master/slides.json',
	),
	'success-links' => array(
		'home' => array(
			'label'  => esc_html__( 'View your site', 'ocularis' ),
			'type'   => 'primary',
			'target' => '_self',
			'icon'   => 'dashicons-welcome-view-site',
			'desc'   => esc_html__( 'Take a look at your site', 'ocularis' ),
			'url'    => home_url( '/' ),
		),
		'customize' => array(
			'label'  => esc_html__( 'Customize your theme', 'ocularis' ),
			'type'   => 'primary',
			'target' => '_self',
			'icon'   => 'dashicons-admin-generic',
			'desc'   => esc_html__( 'Proceed to customizing your theme', 'ocularis' ),
			'url'    => admin_url( 'customize.php' ),
		),
	),
	'export' => array(
		'options' => array(
			'site_icon',
			'elementor_cpt_support',
			'elementor_disable_color_schemes',
			'elementor_disable_typography_schemes',
			'elementor_container_width',
			'elementor_css_print_method',
			'elementor_global_image_lightbox',
			'jet-elements-settings',
			'jet_menu_options',
			'woocommerce_default_country',
				'woocommerce_shop_page_id',
				'woocommerce_techguide_page_id',
				'woocommerce_default_catalog_orderby',
				'techguide_catalog_image_size',
				'techguide_single_image_size',
				'techguide_thumbnail_image_size',
				'woocommerce_cart_page_id',
				'woocommerce_checkout_page_id',
				'woocommerce_terms_page_id',
				'tm_woowishlist_page',
				'tm_woocompare_page',
				'tm_woocompare_enable',
				'tm_woocompare_show_in_catalog',
				'tm_woocompare_show_in_single',
				'tm_woocompare_compare_text',
				'tm_woocompare_remove_text',
				'tm_woocompare_page_btn_text',
				'tm_woocompare_show_in_catalog',
				'site_icon',
				'elementor_cpt_support',
				'elementor_disable_color_schemes',
				'elementor_disable_typography_schemes',
				'elementor_container_width',
				'elementor_css_print_method',
				'elementor_global_image_lightbox',
				'jet-elements-settings',
				'jet_menu_options',
				'highlight-and-share',
				'stockticker_defaults',
				'wsl_settings_social_icon_set',
				'jet_woo_builder',
				'jet-cw-settings',
		),
		'tables' => array(
			'revslider_css',
			'revslider_layer_animations',
			'revslider_navigations',
			'revslider_sliders',
			'revslider_slides',
			'revslider_static_slides',
		),
	),
);
